server:
   tomcat:
      basedir: ${application.home}
      max-threads: 10
      access-log-enabled: true
      access-log-pattern: "%t lbip=%h identd=%l user=%u status=%s method=%m url=%U bytes=%b duration=%D"
   port: 8080
   compression:
     enabled: true
     mime-types: application/json,application/xml,text/html,text/xml,text/plain